# created by jeff per https://guides.rubyonrails.org/v5.2.0/active_storage_overview.html
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
amazon:
  service: S3
  access_key_id: "AWS_ACCESS_KEY_ID"
  secret_access_key: "AWS_SECRET_ACCESS_KEY"
  bucket: "PRODUCTION_S3_BUCKET"